package(
    default_visibility = [
        "//sweeping_robot:internal"
    ],
)

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

package_group(
    name = "internal",
    packages = [
        "//sweeping_robot/...",
    ],
)
