package(
    default_visibility = [
        "//sweeping_robot:internal"
    ],
)

cc_library(
    name = "listener",
    hdrs = ["listener.h"],
    deps = [
        "@github_com_horanceliu_cub//cub/base:keywords",
    ],
)
